"""This is constants file."""
DELETED = 'deleted'
ADDED = 'added'
UNCHANGED = 'unchanged'
CHANGED = 'changed'
NESTED = 'nested'
CONDITION = 'condition'
VALUE = 'value'
NEW_VALUE = 'new_value'
OLD_VALUE = 'old_value'
